version: "3"

services:
  #Persistent database
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: frontier
      TZ: Europe/London
    networks:
      postgres_net:
        ipv4_address: 172.12.1.4

  # Dummy Mailer
  mail_dev:
    container_name: mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      backend_net:
        ipv4_address: 172.14.1.10

  backend:
    container_name: backend-server
    ports:
      - "80:80"
    environment:
      PORT: 80
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@postgres:5432/frontier
      ENV: production
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      BCRYPT_SALT_ROUNDS: 12

    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python entrypoint.py'
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      postgres_net:
        ipv4_address: 172.12.1.8
      backend_net:
        ipv4_address: 172.14.1.12

networks:
  postgres_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.1.0/24
  backend_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.14.1.0/24

volumes:
  postgres-data: