export { default as About } from './About'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Profile } from './Profile'
export { default as Shop } from './Shop'
export { default as Support } from './Support'
export { default as NotFound } from './NotFound'

export { default as Breathing } from './Breathing'
export { default as FamFri } from './FamFri'
export { default as FreshAir } from './FreshAir'
export { default as Playlist } from './Playlist'
export { default as SelfCare } from './SelfCare'
export { default as Mystery } from './Mystery'

export {default as PasswordReset} from './PasswordReset'
export {default as Welcome} from './Welcome'
