export { default as About } from './About'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Profile } from './Profile'
export { default as Shop } from './Shop'
export { default as Support } from './Support'
export { default as NotFound } from './NotFound'